
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.30.148.22:3306/databasetest?serverTimeZone=UTC&CharacterEncoding=UTF-8
    username: issac
    password: dltkr9511$