REM INSERTING into TEAM4_202011F.CLAUSE
SET DEFINE OFF;
Insert into TEAM4_202011F.CLAUSE (CLAUSE_NO,CLAUSE_TITLE,CLAUSE_REQUIRE,CLAUSE_DEL) values (1,'이용 약관 동의(필수)','Y','N');
Insert into TEAM4_202011F.CLAUSE (CLAUSE_NO,CLAUSE_TITLE,CLAUSE_REQUIRE,CLAUSE_DEL) values (2,'개인정보 수집 및 이용 동의(필수)','Y','N');
Insert into TEAM4_202011F.CLAUSE (CLAUSE_NO,CLAUSE_TITLE,CLAUSE_REQUIRE,CLAUSE_DEL) values (3,'프로모션 정보 수신 동의 (선택)','N','N');
