--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-28-2021   
--------------------------------------------------------
@D:\A_TeachingMaterial\SEQUENCES\ACCUSE_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\ALARMRES_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\APP_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\CAREER_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\CLAUSE_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\COIN_USE_NO_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\EH_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\EMAIL_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\FAC_MANAGE_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\FAC_TREAT_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\FILES_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\INCOME_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\JOB_TEST_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\LACTION_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\POS_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\QNA_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\REPORT_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\REP_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\RM_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\SAL_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\UBOARD_SEQ.sql
@D:\A_TeachingMaterial\SEQUENCES\WORK_SEQ.sql
@D:\A_TeachingMaterial\TABLES\ACCUSE.sql
@D:\A_TeachingMaterial\TABLES\AGREEMENT.sql
@D:\A_TeachingMaterial\TABLES\ALARM.sql
@D:\A_TeachingMaterial\TABLES\ALARM_RECEIVER.sql
@D:\A_TeachingMaterial\TABLES\APPROVAL.sql
@D:\A_TeachingMaterial\TABLES\ATTRACTION.sql
@D:\A_TeachingMaterial\TABLES\BASIC_SALARY.sql
@D:\A_TeachingMaterial\TABLES\CAREER.sql
@D:\A_TeachingMaterial\TABLES\CLAUSE.sql
@D:\A_TeachingMaterial\TABLES\COIN.sql
@D:\A_TeachingMaterial\TABLES\COIN_CHARGE.sql
@D:\A_TeachingMaterial\TABLES\COIN_USE.sql
@D:\A_TeachingMaterial\TABLES\COM_CODE.sql
@D:\A_TeachingMaterial\TABLES\COM_GRP.sql
@D:\A_TeachingMaterial\TABLES\EDU_HISTORY.sql
@D:\A_TeachingMaterial\TABLES\EMAIL.sql
@D:\A_TeachingMaterial\TABLES\EMAIL_RECEIVER.sql
@D:\A_TeachingMaterial\TABLES\EMP.sql
@D:\A_TeachingMaterial\TABLES\EMP_FILES.sql
@D:\A_TeachingMaterial\TABLES\EMP_LISENCE.sql
@D:\A_TeachingMaterial\TABLES\FACILITIES.sql
@D:\A_TeachingMaterial\TABLES\FAC_MANAGE.sql
@D:\A_TeachingMaterial\TABLES\FAC_TREAT.sql
@D:\A_TeachingMaterial\TABLES\FILES.sql
@D:\A_TeachingMaterial\TABLES\INCOME.sql
@D:\A_TeachingMaterial\TABLES\JOB_TEST01.sql
@D:\A_TeachingMaterial\TABLES\LACTION.sql
@D:\A_TeachingMaterial\TABLES\LACTION_SELECT.sql
@D:\A_TeachingMaterial\TABLES\LIFE_PROD.sql
@D:\A_TeachingMaterial\TABLES\LISENCES.sql
@D:\A_TeachingMaterial\TABLES\LPROD.sql
@D:\A_TeachingMaterial\TABLES\MEMBERSHIP.sql
@D:\A_TeachingMaterial\TABLES\MENU.sql
@D:\A_TeachingMaterial\TABLES\MENU_AUTH.sql
@D:\A_TeachingMaterial\TABLES\PAY.sql
@D:\A_TeachingMaterial\TABLES\POS.sql
@D:\A_TeachingMaterial\TABLES\PROD.sql
@D:\A_TeachingMaterial\TABLES\QNA.sql
@D:\A_TeachingMaterial\TABLES\READY_MONEY.sql
@D:\A_TeachingMaterial\TABLES\RENT.sql
@D:\A_TeachingMaterial\TABLES\REPORT.sql
@D:\A_TeachingMaterial\TABLES\RESERVE.sql
@D:\A_TeachingMaterial\TABLES\RES_INFO.sql
@D:\A_TeachingMaterial\TABLES\SALARY.sql
@D:\A_TeachingMaterial\TABLES\SALE.sql
@D:\A_TeachingMaterial\TABLES\TICKET.sql
@D:\A_TeachingMaterial\TABLES\TO_SALES.sql
@D:\A_TeachingMaterial\TABLES\UBOARD.sql
@D:\A_TeachingMaterial\TABLES\USERS.sql
@D:\A_TeachingMaterial\TABLES\VACATION.sql
@D:\A_TeachingMaterial\TABLES\WORK.sql
@D:\A_TeachingMaterial\VIEWS\ALL_RES_INFO_VIEW.sql
@D:\A_TeachingMaterial\VIEWS\COIN_HISTORY_VIEW.sql
@D:\A_TeachingMaterial\VIEWS\COIN_TOTAL_USE.sql
@D:\A_TeachingMaterial\VIEWS\COM_CODE_GRP_VIEW.sql
@D:\A_TeachingMaterial\VIEWS\DEL_COIN_CHARGE.sql
@D:\A_TeachingMaterial\VIEWS\DEL_COIN_CODE.sql
@D:\A_TeachingMaterial\VIEWS\DEL_COIN_USE.sql
@D:\A_TeachingMaterial\VIEWS\DEL_RES_CODE.sql
@D:\A_TeachingMaterial\VIEWS\DEL_RES_INFO_CODE.sql
@D:\A_TeachingMaterial\VIEWS\DEL_USERS_ID.sql
@D:\A_TeachingMaterial\VIEWS\EMAIL_VIEW.sql
@D:\A_TeachingMaterial\VIEWS\FC_ATT_FILES_VIEW.sql
@D:\A_TeachingMaterial\VIEWS\FC_ATT_VIEW.sql
@D:\A_TeachingMaterial\VIEWS\STOCK_VIEW.sql
@D:\A_TeachingMaterial\VIEWS\TODAY_TOTAL_AMOUNT_VIEW.sql
@D:\A_TeachingMaterial\VIEWS\TOTAL_RESERVE_VIEW.sql
@D:\A_TeachingMaterial\VIEWS\USER_AUTH_VIEW.sql
@D:\A_TeachingMaterial\VIEWS\USER_RES_INFO_VIEW.sql
@D:\A_TeachingMaterial\VIEWS\USER_RES_VIEW.sql
@D:\A_TeachingMaterial\DATA_TABLE\ACCUSE.sql
@D:\A_TeachingMaterial\DATA_TABLE\AGREEMENT.sql
@D:\A_TeachingMaterial\DATA_TABLE\ALARM.sql
@D:\A_TeachingMaterial\DATA_TABLE\ALARM_RECEIVER.sql
@D:\A_TeachingMaterial\DATA_TABLE\APPROVAL.sql
@D:\A_TeachingMaterial\DATA_TABLE\ATTRACTION.sql
@D:\A_TeachingMaterial\DATA_TABLE\BASIC_SALARY.sql
@D:\A_TeachingMaterial\DATA_TABLE\CAREER.sql
@D:\A_TeachingMaterial\DATA_TABLE\CLAUSE.sql
@D:\A_TeachingMaterial\DATA_TABLE\COIN.sql
@D:\A_TeachingMaterial\DATA_TABLE\COIN_CHARGE.sql
@D:\A_TeachingMaterial\DATA_TABLE\COIN_USE.sql
@D:\A_TeachingMaterial\DATA_TABLE\COM_CODE.sql
@D:\A_TeachingMaterial\DATA_TABLE\COM_GRP.sql
@D:\A_TeachingMaterial\DATA_TABLE\EDU_HISTORY.sql
@D:\A_TeachingMaterial\DATA_TABLE\EMAIL.sql
@D:\A_TeachingMaterial\DATA_TABLE\EMAIL_RECEIVER.sql
@D:\A_TeachingMaterial\DATA_TABLE\EMP.sql
@D:\A_TeachingMaterial\DATA_TABLE\EMP_FILES.sql
@D:\A_TeachingMaterial\DATA_TABLE\EMP_LISENCE.sql
@D:\A_TeachingMaterial\DATA_TABLE\FACILITIES.sql
@D:\A_TeachingMaterial\DATA_TABLE\FAC_MANAGE.sql
@D:\A_TeachingMaterial\DATA_TABLE\FAC_TREAT.sql
@D:\A_TeachingMaterial\DATA_TABLE\FILES.sql
@D:\A_TeachingMaterial\DATA_TABLE\INCOME.sql
@D:\A_TeachingMaterial\DATA_TABLE\JOB_TEST01.sql
@D:\A_TeachingMaterial\DATA_TABLE\LACTION.sql
@D:\A_TeachingMaterial\DATA_TABLE\LACTION_SELECT.sql
@D:\A_TeachingMaterial\DATA_TABLE\LIFE_PROD.sql
@D:\A_TeachingMaterial\DATA_TABLE\LISENCES.sql
@D:\A_TeachingMaterial\DATA_TABLE\LPROD.sql
@D:\A_TeachingMaterial\DATA_TABLE\MEMBERSHIP.sql
@D:\A_TeachingMaterial\DATA_TABLE\MENU.sql
@D:\A_TeachingMaterial\DATA_TABLE\MENU_AUTH.sql
@D:\A_TeachingMaterial\DATA_TABLE\PAY.sql
@D:\A_TeachingMaterial\DATA_TABLE\POS.sql
@D:\A_TeachingMaterial\DATA_TABLE\PROD.sql
@D:\A_TeachingMaterial\DATA_TABLE\QNA.sql
@D:\A_TeachingMaterial\DATA_TABLE\READY_MONEY.sql
@D:\A_TeachingMaterial\DATA_TABLE\RENT.sql
@D:\A_TeachingMaterial\DATA_TABLE\REPORT.sql
@D:\A_TeachingMaterial\DATA_TABLE\RESERVE.sql
@D:\A_TeachingMaterial\DATA_TABLE\RES_INFO.sql
@D:\A_TeachingMaterial\DATA_TABLE\SALARY.sql
@D:\A_TeachingMaterial\DATA_TABLE\SALE.sql
@D:\A_TeachingMaterial\DATA_TABLE\TICKET.sql
@D:\A_TeachingMaterial\DATA_TABLE\TO_SALES.sql
@D:\A_TeachingMaterial\DATA_TABLE\UBOARD.sql
@D:\A_TeachingMaterial\DATA_TABLE\USERS.sql
@D:\A_TeachingMaterial\DATA_TABLE\VACATION.sql
@D:\A_TeachingMaterial\DATA_TABLE\WORK.sql
@D:\A_TeachingMaterial\INDEXES\PK_QNA.sql
@D:\A_TeachingMaterial\INDEXES\PK_COIN.sql
@D:\A_TeachingMaterial\INDEXES\PK_ATTRACTION.sql
@D:\A_TeachingMaterial\INDEXES\PK_FAC_MANAGE.sql
@D:\A_TeachingMaterial\INDEXES\PK_PROD.sql
@D:\A_TeachingMaterial\INDEXES\PK_EMP.sql
@D:\A_TeachingMaterial\INDEXES\PK_FAC_TREAT.sql
@D:\A_TeachingMaterial\INDEXES\PK_COM_GRP.sql
@D:\A_TeachingMaterial\INDEXES\PK_USERS.sql
@D:\A_TeachingMaterial\INDEXES\PK_LACTION_SELECT.sql
@D:\A_TeachingMaterial\INDEXES\PK_ALARM_RECEIVER.sql
@D:\A_TeachingMaterial\INDEXES\PK_WORK.sql
@D:\A_TeachingMaterial\INDEXES\PK_COIN_USE.sql
@D:\A_TeachingMaterial\INDEXES\PK_TO_SALES.sql
@D:\A_TeachingMaterial\INDEXES\PK_LACTION.sql
@D:\A_TeachingMaterial\INDEXES\PK_FILES.sql
@D:\A_TeachingMaterial\INDEXES\PK_MENU_AUTH.sql
@D:\A_TeachingMaterial\INDEXES\PK_SALE.sql
@D:\A_TeachingMaterial\INDEXES\PK_EDU.sql
@D:\A_TeachingMaterial\INDEXES\PK_AGREEMENT.sql
@D:\A_TeachingMaterial\INDEXES\PK_FACILITIES.sql
@D:\A_TeachingMaterial\INDEXES\PK_RES_INFO.sql
@D:\A_TeachingMaterial\INDEXES\PK_POS.sql
@D:\A_TeachingMaterial\INDEXES\PK_ACCUSE.sql
@D:\A_TeachingMaterial\INDEXES\PK_PAY.sql
@D:\A_TeachingMaterial\INDEXES\PK_INCOME.sql
@D:\A_TeachingMaterial\INDEXES\PK_RM.sql
@D:\A_TeachingMaterial\INDEXES\PK_LISENCES.sql
@D:\A_TeachingMaterial\INDEXES\PK_VACATION.sql
@D:\A_TeachingMaterial\INDEXES\PK_COIN_CHARGE.sql
@D:\A_TeachingMaterial\INDEXES\PK_EMP_FILES.sql
@D:\A_TeachingMaterial\INDEXES\PK_MENU.sql
@D:\A_TeachingMaterial\INDEXES\PK_APPROVAL.sql
@D:\A_TeachingMaterial\INDEXES\PK_EMAIL.sql
@D:\A_TeachingMaterial\INDEXES\PK_CLAUSE.sql
@D:\A_TeachingMaterial\INDEXES\PK_UBOARD.sql
@D:\A_TeachingMaterial\INDEXES\PK_COMMON_CODE.sql
@D:\A_TeachingMaterial\INDEXES\PK_RESERVE.sql
@D:\A_TeachingMaterial\INDEXES\PK_RENT.sql
@D:\A_TeachingMaterial\INDEXES\PK_ALARM.sql
@D:\A_TeachingMaterial\INDEXES\PK_REPORT.sql
@D:\A_TeachingMaterial\INDEXES\PK_LPROD.sql
@D:\A_TeachingMaterial\INDEXES\PK_SALARY.sql
@D:\A_TeachingMaterial\INDEXES\PK_EMP_LISENCE.sql
@D:\A_TeachingMaterial\INDEXES\PK_LIFE_PROD.sql
@D:\A_TeachingMaterial\INDEXES\PK_EMAIL_RECEIVER.sql
@D:\A_TeachingMaterial\INDEXES\PK_BASIC_SALARY.sql
@D:\A_TeachingMaterial\INDEXES\PK_CAREER.sql
@D:\A_TeachingMaterial\INDEXES\PK_MEMBERSHIP.sql
@D:\A_TeachingMaterial\INDEXES\PK_TICKET.sql
@D:\A_TeachingMaterial\TRIGGERS\ALARM_RECEIVER_INSER.sql
@D:\A_TeachingMaterial\TRIGGERS\COIN_CANCLE_CHARGE.sql
@D:\A_TeachingMaterial\TRIGGERS\COIN_PROD_BACK.sql
@D:\A_TeachingMaterial\TRIGGERS\COIN_PROD_USE.sql
@D:\A_TeachingMaterial\PROCEDURES\CREATE_RES_PAY_PROC.sql
@D:\A_TeachingMaterial\PROCEDURES\EMP_RESET_VACATION.sql
@D:\A_TeachingMaterial\PROCEDURES\GUEST_DELETE_COIN_CHARGE.sql
@D:\A_TeachingMaterial\PROCEDURES\GUEST_DELETE_COIN_CODE.sql
@D:\A_TeachingMaterial\PROCEDURES\GUEST_DELETE_COIN_USE.sql
@D:\A_TeachingMaterial\PROCEDURES\GUEST_DELETE_RES_CODE.sql
@D:\A_TeachingMaterial\PROCEDURES\GUEST_DELETE_RES_INFO_CODE.sql
@D:\A_TeachingMaterial\PROCEDURES\GUEST_DELETE_USERS_ID.sql
@D:\A_TeachingMaterial\PROCEDURES\INSERT_RES_INFO_PROC.sql
@D:\A_TeachingMaterial\PROCEDURES\RES_PAY_PROC.sql
@D:\A_TeachingMaterial\FUNCTIONS\GET_A_STOCK_FUNC.sql
@D:\A_TeachingMaterial\FUNCTIONS\GET_CODE_NAME_FUNC.sql
@D:\A_TeachingMaterial\FUNCTIONS\GET_EMAIL_RECEIVE_DATE.sql
@D:\A_TeachingMaterial\FUNCTIONS\GET_KORNM.sql
@D:\A_TeachingMaterial\CONSTRAINTS\EDU_HISTORY.sql
@D:\A_TeachingMaterial\CONSTRAINTS\LISENCES.sql
@D:\A_TeachingMaterial\CONSTRAINTS\ALARM_RECEIVER.sql
@D:\A_TeachingMaterial\CONSTRAINTS\SALARY.sql
@D:\A_TeachingMaterial\CONSTRAINTS\COIN_CHARGE.sql
@D:\A_TeachingMaterial\CONSTRAINTS\READY_MONEY.sql
@D:\A_TeachingMaterial\CONSTRAINTS\TO_SALES.sql
@D:\A_TeachingMaterial\CONSTRAINTS\FILES.sql
@D:\A_TeachingMaterial\CONSTRAINTS\RENT.sql
@D:\A_TeachingMaterial\CONSTRAINTS\COM_GRP.sql
@D:\A_TeachingMaterial\CONSTRAINTS\BASIC_SALARY.sql
@D:\A_TeachingMaterial\CONSTRAINTS\FAC_TREAT.sql
@D:\A_TeachingMaterial\CONSTRAINTS\LACTION_SELECT.sql
@D:\A_TeachingMaterial\CONSTRAINTS\POS.sql
@D:\A_TeachingMaterial\CONSTRAINTS\VACATION.sql
@D:\A_TeachingMaterial\CONSTRAINTS\AGREEMENT.sql
@D:\A_TeachingMaterial\CONSTRAINTS\UBOARD.sql
@D:\A_TeachingMaterial\CONSTRAINTS\RESERVE.sql
@D:\A_TeachingMaterial\CONSTRAINTS\EMAIL.sql
@D:\A_TeachingMaterial\CONSTRAINTS\COIN_USE.sql
@D:\A_TeachingMaterial\CONSTRAINTS\ALARM.sql
@D:\A_TeachingMaterial\CONSTRAINTS\APPROVAL.sql
@D:\A_TeachingMaterial\CONSTRAINTS\LPROD.sql
@D:\A_TeachingMaterial\CONSTRAINTS\FAC_MANAGE.sql
@D:\A_TeachingMaterial\CONSTRAINTS\LACTION.sql
@D:\A_TeachingMaterial\CONSTRAINTS\LIFE_PROD.sql
@D:\A_TeachingMaterial\CONSTRAINTS\REPORT.sql
@D:\A_TeachingMaterial\CONSTRAINTS\CAREER.sql
@D:\A_TeachingMaterial\CONSTRAINTS\EMP_FILES.sql
@D:\A_TeachingMaterial\CONSTRAINTS\FACILITIES.sql
@D:\A_TeachingMaterial\CONSTRAINTS\QNA.sql
@D:\A_TeachingMaterial\CONSTRAINTS\ACCUSE.sql
@D:\A_TeachingMaterial\CONSTRAINTS\SALE.sql
@D:\A_TeachingMaterial\CONSTRAINTS\ATTRACTION.sql
@D:\A_TeachingMaterial\CONSTRAINTS\TICKET.sql
@D:\A_TeachingMaterial\CONSTRAINTS\COM_CODE.sql
@D:\A_TeachingMaterial\CONSTRAINTS\EMAIL_RECEIVER.sql
@D:\A_TeachingMaterial\CONSTRAINTS\RES_INFO.sql
@D:\A_TeachingMaterial\CONSTRAINTS\COIN.sql
@D:\A_TeachingMaterial\CONSTRAINTS\EMP_LISENCE.sql
@D:\A_TeachingMaterial\CONSTRAINTS\MENU.sql
@D:\A_TeachingMaterial\CONSTRAINTS\PROD.sql
@D:\A_TeachingMaterial\CONSTRAINTS\PAY.sql
@D:\A_TeachingMaterial\CONSTRAINTS\USERS.sql
@D:\A_TeachingMaterial\CONSTRAINTS\WORK.sql
@D:\A_TeachingMaterial\CONSTRAINTS\MEMBERSHIP.sql
@D:\A_TeachingMaterial\CONSTRAINTS\EMP.sql
@D:\A_TeachingMaterial\CONSTRAINTS\INCOME.sql
@D:\A_TeachingMaterial\CONSTRAINTS\CLAUSE.sql
@D:\A_TeachingMaterial\CONSTRAINTS\MENU_AUTH.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\ACCUSE.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\AGREEMENT.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\ALARM.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\ALARM_RECEIVER.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\APPROVAL.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\ATTRACTION.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\CAREER.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\COIN.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\COIN_CHARGE.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\COIN_USE.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\COM_CODE.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\EDU_HISTORY.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\EMAIL.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\EMAIL_RECEIVER.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\EMP.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\EMP_FILES.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\EMP_LISENCE.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\FAC_MANAGE.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\FAC_TREAT.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\INCOME.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\LACTION_SELECT.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\LIFE_PROD.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\MEMBERSHIP.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\MENU.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\MENU_AUTH.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\PAY.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\POS.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\PROD.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\QNA.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\READY_MONEY.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\RENT.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\REPORT.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\RESERVE.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\RES_INFO.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\SALARY.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\TO_SALES.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\VACATION.sql
@D:\A_TeachingMaterial\REF_CONSTRAINTS\WORK.sql
