--------------------------------------------------------
--  Constraints for Table BASIC_SALARY
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."BASIC_SALARY" ADD CONSTRAINT "PK_BASIC_SALARY" PRIMARY KEY ("RESPONSE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."BASIC_SALARY" MODIFY ("BASIC_SAL" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."BASIC_SALARY" MODIFY ("RESPONSE_CODE" NOT NULL ENABLE);
