--------------------------------------------------------
--  Constraints for Table CAREER
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."CAREER" ADD CONSTRAINT "PK_CAREER" PRIMARY KEY ("CAREER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."CAREER" MODIFY ("CAREER_POSITION" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."CAREER" MODIFY ("CAREER_END" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."CAREER" MODIFY ("CAREER_START" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."CAREER" MODIFY ("CAREER_COM_ADDR" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."CAREER" MODIFY ("CAREER_COM" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."CAREER" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."CAREER" MODIFY ("CAREER_NO" NOT NULL ENABLE);
