--------------------------------------------------------
--  Constraints for Table COIN_CHARGE
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."COIN_CHARGE" ADD CONSTRAINT "PK_COIN_CHARGE" PRIMARY KEY ("COIN_CHARGE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."COIN_CHARGE" MODIFY ("COIN_CHARGE_STATE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."COIN_CHARGE" MODIFY ("COIN_CHARGE_DATE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."COIN_CHARGE" MODIFY ("COIN_CHARGE_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."COIN_CHARGE" MODIFY ("COIN_CODE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."COIN_CHARGE" MODIFY ("COIN_CHARGE_CODE" NOT NULL ENABLE);
