--------------------------------------------------------
--  Constraints for Table COM_CODE
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."COM_CODE" ADD CONSTRAINT "PK_COMMON_CODE" PRIMARY KEY ("COM_CODE", "COM_CODE_GRP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."COM_CODE" MODIFY ("CODE_COL" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."COM_CODE" MODIFY ("COM_CODE_DESC" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."COM_CODE" MODIFY ("COM_CODE_NAME" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."COM_CODE" MODIFY ("COM_CODE_GRP" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."COM_CODE" MODIFY ("COM_CODE" NOT NULL ENABLE);
