--------------------------------------------------------
--  Constraints for Table COM_GRP
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."COM_GRP" ADD CONSTRAINT "PK_COM_GRP" PRIMARY KEY ("COM_CODE_GRP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."COM_GRP" MODIFY ("COM_CODE_GRP_NAME" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."COM_GRP" MODIFY ("COM_CODE_GRP" NOT NULL ENABLE);
