--------------------------------------------------------
--  Constraints for Table EMAIL_RECEIVER
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."EMAIL_RECEIVER" MODIFY ("RECEIVE_DEL" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."EMAIL_RECEIVER" ADD CONSTRAINT "PK_EMAIL_RECEIVER" PRIMARY KEY ("EMP_ID", "EMAIL_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."EMAIL_RECEIVER" MODIFY ("EMAIL_NO" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."EMAIL_RECEIVER" MODIFY ("EMP_ID" NOT NULL ENABLE);
