--------------------------------------------------------
--  Constraints for Table EMP
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."EMP" ADD CONSTRAINT "PK_EMP" PRIMARY KEY ("EMP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."EMP" MODIFY ("EMP_PROTECT" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."EMP" MODIFY ("EMP_VAC" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."EMP" MODIFY ("EMP_HIRE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."EMP" MODIFY ("TEAM_CODE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."EMP" MODIFY ("EMP_MAIL" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."EMP" MODIFY ("RESPONSE_CODE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."EMP" MODIFY ("EMP_NAME" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."EMP" MODIFY ("EMP_PASS" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."EMP" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."EMP" MODIFY ("EMP_DEL" NOT NULL ENABLE);
