--------------------------------------------------------
--  Constraints for Table EMP_LISENCE
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."EMP_LISENCE" ADD CONSTRAINT "PK_EMP_LISENCE" PRIMARY KEY ("LISENCE_CODE", "EMP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."EMP_LISENCE" MODIFY ("LISENCE_EXP" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."EMP_LISENCE" MODIFY ("LISENCE_GET" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."EMP_LISENCE" MODIFY ("LISENCE_PN" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."EMP_LISENCE" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."EMP_LISENCE" MODIFY ("LISENCE_CODE" NOT NULL ENABLE);
