--------------------------------------------------------
--  Constraints for Table FAC_TREAT
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."FAC_TREAT" ADD CONSTRAINT "PK_FAC_TREAT" PRIMARY KEY ("FT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."FAC_TREAT" MODIFY ("FT_DEL" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."FAC_TREAT" MODIFY ("FT_CHECK" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."FAC_TREAT" MODIFY ("FT_CONT" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."FAC_TREAT" MODIFY ("FT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."FAC_TREAT" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."FAC_TREAT" MODIFY ("FM_CODE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."FAC_TREAT" MODIFY ("FT_NO" NOT NULL ENABLE);
