--------------------------------------------------------
--  Constraints for Table FILES
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."FILES" ADD CONSTRAINT "PK_FILES" PRIMARY KEY ("FILE_NO", "FILE_ORD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."FILES" MODIFY ("FILE_DEL" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."FILES" MODIFY ("FILE_SAVE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."FILES" MODIFY ("FILE_ORIGIN" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."FILES" MODIFY ("FILE_PATH" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."FILES" MODIFY ("FILE_ORD" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."FILES" MODIFY ("FILE_NO" NOT NULL ENABLE);
