--------------------------------------------------------
--  Constraints for Table LISENCES
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."LISENCES" ADD CONSTRAINT "PK_LISENCES" PRIMARY KEY ("LISENCE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."LISENCES" MODIFY ("LISENCE_PUB" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."LISENCES" MODIFY ("LISENCE_NAME" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."LISENCES" MODIFY ("LISENCE_CODE" NOT NULL ENABLE);
