--------------------------------------------------------
--  Constraints for Table LPROD
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."LPROD" ADD CONSTRAINT "PK_LPROD" PRIMARY KEY ("LPROD_CODE", "PROD_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."LPROD" MODIFY ("PROD_NAME" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."LPROD" MODIFY ("LPROD_CODE" NOT NULL ENABLE);
