--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."MENU" ADD CONSTRAINT "PK_MENU" PRIMARY KEY ("MENU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."MENU" MODIFY ("MENU_URL" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."MENU" MODIFY ("MENU_DESC" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."MENU" MODIFY ("MENU_NAME" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."MENU" MODIFY ("MENU_ORD" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."MENU" MODIFY ("MENU_SE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."MENU" MODIFY ("MENU_ID" NOT NULL ENABLE);
