--------------------------------------------------------
--  Constraints for Table PAY
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."PAY" ADD CONSTRAINT "PK_PAY" PRIMARY KEY ("RES_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."PAY" MODIFY ("PAY_WAY" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."PAY" MODIFY ("PAY_METHOD" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."PAY" MODIFY ("PAY_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."PAY" MODIFY ("PAY_DATE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."PAY" MODIFY ("RES_CODE" NOT NULL ENABLE);
