--------------------------------------------------------
--  Constraints for Table REPORT
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY ("REPORT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."REPORT" MODIFY ("REPORT_DEL" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."REPORT" MODIFY ("LREPORT_CODE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."REPORT" MODIFY ("REPORT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."REPORT" MODIFY ("REPORT_CONT" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."REPORT" MODIFY ("REPORT_TITLE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."REPORT" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."REPORT" MODIFY ("REPORT_NO" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."REPORT" MODIFY ("REPORT_APP_NEED" NOT NULL ENABLE);
