--------------------------------------------------------
--  Constraints for Table RES_INFO
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."RES_INFO" ADD CONSTRAINT "PK_RES_INFO" PRIMARY KEY ("RES_INFO_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."RES_INFO" MODIFY ("TICKET_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."RES_INFO" MODIFY ("RES_CODE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."RES_INFO" MODIFY ("RES_INFO_CODE" NOT NULL ENABLE);
