--------------------------------------------------------
--  Constraints for Table SALARY
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."SALARY" ADD CONSTRAINT "PK_SALARY" PRIMARY KEY ("SAL_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."SALARY" MODIFY ("SAL_HEALTH" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."SALARY" MODIFY ("SAL_SAFE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."SALARY" MODIFY ("SAL_EMPINS" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."SALARY" MODIFY ("SAL_NATION" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."SALARY" MODIFY ("SAL_DATE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."SALARY" MODIFY ("SAL_CONT" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."SALARY" MODIFY ("SAL_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."SALARY" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."SALARY" MODIFY ("SAL_NO" NOT NULL ENABLE);
