--------------------------------------------------------
--  Constraints for Table SALE
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."SALE" ADD CONSTRAINT "PK_SALE" PRIMARY KEY ("SALE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."SALE" MODIFY ("SALE_END" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."SALE" MODIFY ("SALE_START" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."SALE" MODIFY ("SALE_WHO" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."SALE" MODIFY ("SALE_WAY" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."SALE" MODIFY ("SALE_PERCENT" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."SALE" MODIFY ("SALE_NAME" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."SALE" MODIFY ("SALE_ID" NOT NULL ENABLE);
