--------------------------------------------------------
--  Constraints for Table TO_SALES
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."TO_SALES" ADD CONSTRAINT "PK_TO_SALES" PRIMARY KEY ("RES_CODE", "FC_ID", "EMP_ID", "POS_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."TO_SALES" MODIFY ("POS_NO" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."TO_SALES" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."TO_SALES" MODIFY ("FC_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."TO_SALES" MODIFY ("RES_CODE" NOT NULL ENABLE);
