--------------------------------------------------------
--  Constraints for Table UBOARD
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."UBOARD" ADD CONSTRAINT "PK_UBOARD" PRIMARY KEY ("UBOARD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."UBOARD" MODIFY ("LUBOARD_CODE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."UBOARD" MODIFY ("UBOARD_DEL" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."UBOARD" MODIFY ("UBOARD_CONT" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."UBOARD" MODIFY ("UBOARD_TITLE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."UBOARD" MODIFY ("UBOARD_NO" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."UBOARD" MODIFY ("UBOARD_HIT" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."UBOARD" MODIFY ("UBOARD_DATE" NOT NULL ENABLE);
