--------------------------------------------------------
--  Constraints for Table WORK
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."WORK" ADD CONSTRAINT "PK_WORK" PRIMARY KEY ("WORK_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F"  ENABLE;
  ALTER TABLE "TEAM4_202011F"."WORK" MODIFY ("WORK_DATE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."WORK" MODIFY ("LWORK_CODE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."WORK" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."WORK" MODIFY ("WORK_NO" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."WORK" MODIFY ("WORK_TITLE" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."WORK" MODIFY ("WORK_TEXT" NOT NULL ENABLE);
  ALTER TABLE "TEAM4_202011F"."WORK" MODIFY ("WORK_BACK" NOT NULL ENABLE);
