--------------------------------------------------------
--  DDL for Table AGREEMENT
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."AGREEMENT" 
   (	"CLAUSE_NO" NUMBER, 
	"USER_ID" VARCHAR2(12 BYTE), 
	"AGREEMENT_CHECK" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"AGREEMENT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" ;

   COMMENT ON COLUMN "TEAM4_202011F"."AGREEMENT"."CLAUSE_NO" IS '약관 일련 번호';
   COMMENT ON COLUMN "TEAM4_202011F"."AGREEMENT"."USER_ID" IS '회원아이디';
   COMMENT ON COLUMN "TEAM4_202011F"."AGREEMENT"."AGREEMENT_CHECK" IS '약관 동의 여부';
   COMMENT ON COLUMN "TEAM4_202011F"."AGREEMENT"."AGREEMENT_DATE" IS '약관 동의 일시';
   COMMENT ON TABLE "TEAM4_202011F"."AGREEMENT"  IS '약관 동의 내역';
