--------------------------------------------------------
--  DDL for Table CAREER
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."CAREER" 
   (	"CAREER_NO" NUMBER, 
	"EMP_ID" VARCHAR2(12 BYTE), 
	"CAREER_COM" VARCHAR2(100 BYTE), 
	"CAREER_COM_ADDR" VARCHAR2(255 BYTE), 
	"CAREER_START" VARCHAR2(8 BYTE), 
	"CAREER_END" VARCHAR2(8 BYTE), 
	"CAREER_POSITION" VARCHAR2(200 BYTE), 
	"FILE_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" ;

   COMMENT ON COLUMN "TEAM4_202011F"."CAREER"."CAREER_NO" IS '번호';
   COMMENT ON COLUMN "TEAM4_202011F"."CAREER"."EMP_ID" IS '직원 아이디';
   COMMENT ON COLUMN "TEAM4_202011F"."CAREER"."CAREER_COM" IS '회사명';
   COMMENT ON COLUMN "TEAM4_202011F"."CAREER"."CAREER_COM_ADDR" IS '회사 주소';
   COMMENT ON COLUMN "TEAM4_202011F"."CAREER"."CAREER_START" IS '입사일';
   COMMENT ON COLUMN "TEAM4_202011F"."CAREER"."CAREER_END" IS '퇴사일';
   COMMENT ON COLUMN "TEAM4_202011F"."CAREER"."CAREER_POSITION" IS '담당 업무';
   COMMENT ON COLUMN "TEAM4_202011F"."CAREER"."FILE_NO" IS '파일 번호';
