--------------------------------------------------------
--  DDL for Table CLAUSE
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."CLAUSE" 
   (	"CLAUSE_NO" NUMBER, 
	"CLAUSE_TITLE" VARCHAR2(100 BYTE), 
	"CLAUSE_CONT" CLOB, 
	"CLAUSE_REQUIRE" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"CLAUSE_DEL" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" 
 LOB ("CLAUSE_CONT") STORE AS BASICFILE (
  TABLESPACE "TS_202011F" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "TEAM4_202011F"."CLAUSE"."CLAUSE_NO" IS '약관 일련 번호';
   COMMENT ON COLUMN "TEAM4_202011F"."CLAUSE"."CLAUSE_TITLE" IS '약관 제목';
   COMMENT ON COLUMN "TEAM4_202011F"."CLAUSE"."CLAUSE_CONT" IS '약관 내용';
   COMMENT ON COLUMN "TEAM4_202011F"."CLAUSE"."CLAUSE_REQUIRE" IS '약관 필수 여부';
   COMMENT ON COLUMN "TEAM4_202011F"."CLAUSE"."CLAUSE_DEL" IS '약관 삭제 여부';
   COMMENT ON TABLE "TEAM4_202011F"."CLAUSE"  IS '약관';
