--------------------------------------------------------
--  DDL for Table COIN_USE
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."COIN_USE" 
   (	"COIN_USE_CODE" VARCHAR2(12 BYTE), 
	"COIN_CODE" VARCHAR2(12 BYTE), 
	"PROD_CODE" VARCHAR2(12 BYTE), 
	"PROD_PAYCNT" NUMBER, 
	"COIN_USE_DATE" DATE DEFAULT current_timestamp, 
	"COIN_USE_AMOUNT" NUMBER(*,0), 
	"COIN_USE_CANCEL" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" ;

   COMMENT ON COLUMN "TEAM4_202011F"."COIN_USE"."COIN_USE_CODE" IS '포켓코인 사용 코드';
   COMMENT ON COLUMN "TEAM4_202011F"."COIN_USE"."COIN_CODE" IS '포켓코인 코드';
   COMMENT ON COLUMN "TEAM4_202011F"."COIN_USE"."PROD_CODE" IS '판매 상품 코드';
   COMMENT ON COLUMN "TEAM4_202011F"."COIN_USE"."PROD_PAYCNT" IS '상품 결제 수량';
   COMMENT ON COLUMN "TEAM4_202011F"."COIN_USE"."COIN_USE_DATE" IS '포켓코인 사용 일시';
   COMMENT ON COLUMN "TEAM4_202011F"."COIN_USE"."COIN_USE_AMOUNT" IS '포켓코인 사용 금액';
   COMMENT ON COLUMN "TEAM4_202011F"."COIN_USE"."COIN_USE_CANCEL" IS '포켓코인 사용 환불';
   COMMENT ON TABLE "TEAM4_202011F"."COIN_USE"  IS '포켓코인사용';
