--------------------------------------------------------
--  DDL for Table COIN
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."COIN" 
   (	"COIN_CODE" VARCHAR2(12 BYTE), 
	"RES_INFO_CODE" VARCHAR2(12 BYTE), 
	"COIN_START" DATE, 
	"COIN_END" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" ;

   COMMENT ON COLUMN "TEAM4_202011F"."COIN"."COIN_CODE" IS '포켓코인 코드';
   COMMENT ON COLUMN "TEAM4_202011F"."COIN"."RES_INFO_CODE" IS '예매 상세 코드';
   COMMENT ON COLUMN "TEAM4_202011F"."COIN"."COIN_START" IS '발급 일시';
   COMMENT ON COLUMN "TEAM4_202011F"."COIN"."COIN_END" IS '퇴장일시';
   COMMENT ON TABLE "TEAM4_202011F"."COIN"  IS '포켓 코인 발급 내역';
