--------------------------------------------------------
--  DDL for Table EDU_HISTORY
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."EDU_HISTORY" 
   (	"EH_NO" NUMBER, 
	"EMP_ID" VARCHAR2(12 BYTE), 
	"EH_NAME" VARCHAR2(50 BYTE), 
	"EH_DATE" VARCHAR2(13 BYTE), 
	"EH_MAJOR" VARCHAR2(50 BYTE), 
	"EH_DEGREE" VARCHAR2(2 BYTE), 
	"EH_COMPLETE" VARCHAR2(1 BYTE), 
	"FILE_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" ;

   COMMENT ON COLUMN "TEAM4_202011F"."EDU_HISTORY"."EH_NO" IS '번호';
   COMMENT ON COLUMN "TEAM4_202011F"."EDU_HISTORY"."EMP_ID" IS '직원 아이디';
   COMMENT ON COLUMN "TEAM4_202011F"."EDU_HISTORY"."EH_NAME" IS '학교 이름';
   COMMENT ON COLUMN "TEAM4_202011F"."EDU_HISTORY"."EH_DATE" IS '학위기간';
   COMMENT ON COLUMN "TEAM4_202011F"."EDU_HISTORY"."EH_MAJOR" IS '전공';
   COMMENT ON COLUMN "TEAM4_202011F"."EDU_HISTORY"."EH_DEGREE" IS '학위';
   COMMENT ON COLUMN "TEAM4_202011F"."EDU_HISTORY"."EH_COMPLETE" IS '졸업여부';
   COMMENT ON COLUMN "TEAM4_202011F"."EDU_HISTORY"."FILE_NO" IS '파일 번호';
