--------------------------------------------------------
--  DDL for Table EMP
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."EMP" 
   (	"EMP_ID" VARCHAR2(12 BYTE), 
	"EMP_PASS" VARCHAR2(150 BYTE), 
	"EMP_NAME" VARCHAR2(50 BYTE), 
	"EMP_HP" VARCHAR2(11 BYTE), 
	"RESPONSE_CODE" VARCHAR2(2 BYTE), 
	"EMP_MAIL" VARCHAR2(40 BYTE), 
	"TEAM_CODE" VARCHAR2(2 BYTE), 
	"EMP_HIRE" DATE, 
	"EMP_FIRE" DATE, 
	"EMP_VAC" NUMBER, 
	"EMP_PROTECT" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"FC_ID" VARCHAR2(12 BYTE), 
	"EMP_DEL" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"FILE_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" ;

   COMMENT ON COLUMN "TEAM4_202011F"."EMP"."EMP_ID" IS '직원아이디';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP"."EMP_PASS" IS '직원비밀번호';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP"."EMP_NAME" IS '직원명';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP"."EMP_HP" IS '직원 전화번호';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP"."RESPONSE_CODE" IS '직책 코드';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP"."EMP_MAIL" IS '직원이메일';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP"."TEAM_CODE" IS '팀 아이디';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP"."EMP_HIRE" IS '입사일시';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP"."EMP_FIRE" IS '퇴사일시';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP"."EMP_VAC" IS '기본 휴가일';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP"."EMP_PROTECT" IS '직원 보호 계정 여부';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP"."FC_ID" IS '이용 시설물 아이디';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP"."EMP_DEL" IS '직원 삭제 여부';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP"."FILE_NO" IS '직원 첨부 파일 번호';
   COMMENT ON TABLE "TEAM4_202011F"."EMP"  IS '직원';
