--------------------------------------------------------
--  DDL for Table EMP_FILES
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."EMP_FILES" 
   (	"EMP_ID" VARCHAR2(12 BYTE), 
	"FILE_NO" NUMBER, 
	"EMPF_DEL" VARCHAR2(1 BYTE), 
	"LEMPF_CODE" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" ;

   COMMENT ON COLUMN "TEAM4_202011F"."EMP_FILES"."EMP_ID" IS '직원아이디';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP_FILES"."FILE_NO" IS '통합첨부파일번호';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP_FILES"."EMPF_DEL" IS '직원 첨부파일 삭제 여부';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP_FILES"."LEMPF_CODE" IS '직원 첨부파일 분류 코드
';
   COMMENT ON TABLE "TEAM4_202011F"."EMP_FILES"  IS '직원 첨부 파일';
