--------------------------------------------------------
--  DDL for Table EMP_LISENCE
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."EMP_LISENCE" 
   (	"LISENCE_CODE" VARCHAR2(12 BYTE), 
	"EMP_ID" VARCHAR2(12 BYTE), 
	"LISENCE_PN" VARCHAR2(50 BYTE), 
	"LISENCE_GET" VARCHAR2(8 BYTE), 
	"LISENCE_EXP" VARCHAR2(8 BYTE), 
	"FILE_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" ;

   COMMENT ON COLUMN "TEAM4_202011F"."EMP_LISENCE"."LISENCE_CODE" IS '자격증 코드';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP_LISENCE"."EMP_ID" IS '직원아이디';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP_LISENCE"."LISENCE_PN" IS '자격증 발급 번호';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP_LISENCE"."LISENCE_GET" IS '취득일';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP_LISENCE"."LISENCE_EXP" IS '만기일';
   COMMENT ON COLUMN "TEAM4_202011F"."EMP_LISENCE"."FILE_NO" IS '통합첨부파일번호';
   COMMENT ON TABLE "TEAM4_202011F"."EMP_LISENCE"  IS '보유 자격증';
