--------------------------------------------------------
--  DDL for Table FAC_MANAGE
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."FAC_MANAGE" 
   (	"FM_NO" NUMBER, 
	"EMP_ID" VARCHAR2(12 BYTE), 
	"FM_TITLE" VARCHAR2(100 BYTE), 
	"FM_CONT" CLOB, 
	"FM_DATE" VARCHAR2(8 BYTE), 
	"FM_BREAK" VARCHAR2(8 BYTE), 
	"FM_DEL" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"FC_ID" VARCHAR2(12 BYTE), 
	"FILE_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" 
 LOB ("FM_CONT") STORE AS BASICFILE (
  TABLESPACE "TS_202011F" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "TEAM4_202011F"."FAC_MANAGE"."FM_NO" IS '이용 시설물 관리 코드';
   COMMENT ON COLUMN "TEAM4_202011F"."FAC_MANAGE"."EMP_ID" IS '직원아이디';
   COMMENT ON COLUMN "TEAM4_202011F"."FAC_MANAGE"."FM_TITLE" IS '이용 시설물 관리 제목';
   COMMENT ON COLUMN "TEAM4_202011F"."FAC_MANAGE"."FM_CONT" IS '이용 시설물 관리 내용';
   COMMENT ON COLUMN "TEAM4_202011F"."FAC_MANAGE"."FM_DATE" IS '이용 시설물 관리 작성 일자';
   COMMENT ON COLUMN "TEAM4_202011F"."FAC_MANAGE"."FM_BREAK" IS '이용 시설물 고장 일자';
   COMMENT ON COLUMN "TEAM4_202011F"."FAC_MANAGE"."FM_DEL" IS '이용 시설물 관리 삭제 여부';
   COMMENT ON COLUMN "TEAM4_202011F"."FAC_MANAGE"."FC_ID" IS '이용 시설물 아이디';
   COMMENT ON COLUMN "TEAM4_202011F"."FAC_MANAGE"."FILE_NO" IS '통합첨부파일번호';
   COMMENT ON TABLE "TEAM4_202011F"."FAC_MANAGE"  IS '이용 시설물 관리 내역';
