--------------------------------------------------------
--  DDL for Table FACILITIES
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."FACILITIES" 
   (	"FC_ID" VARCHAR2(12 BYTE), 
	"FC_NAME" VARCHAR2(50 BYTE), 
	"LFC_CODE" VARCHAR2(2 BYTE), 
	"FC_PHOTO" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" ;

   COMMENT ON COLUMN "TEAM4_202011F"."FACILITIES"."FC_ID" IS '이용 시설물 아이디';
   COMMENT ON COLUMN "TEAM4_202011F"."FACILITIES"."FC_NAME" IS '이용 시설물 명';
   COMMENT ON COLUMN "TEAM4_202011F"."FACILITIES"."LFC_CODE" IS '이용 시설물 유형';
   COMMENT ON TABLE "TEAM4_202011F"."FACILITIES"  IS '이용 시설물';
