--------------------------------------------------------
--  DDL for Table FILES
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."FILES" 
   (	"FILE_NO" NUMBER, 
	"FILE_ORD" NUMBER, 
	"FILE_BIZ" VARCHAR2(2 BYTE), 
	"FILE_PATH" VARCHAR2(500 BYTE), 
	"FILE_ORIGIN" VARCHAR2(150 BYTE), 
	"FILE_SAVE" VARCHAR2(500 BYTE), 
	"FILE_TYPE" VARCHAR2(100 BYTE), 
	"FILE_DEL" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" ;

   COMMENT ON COLUMN "TEAM4_202011F"."FILES"."FILE_NO" IS '통합첨부파일일련번호';
   COMMENT ON COLUMN "TEAM4_202011F"."FILES"."FILE_ORD" IS '첨부파일순번';
   COMMENT ON COLUMN "TEAM4_202011F"."FILES"."FILE_BIZ" IS '업무구분';
   COMMENT ON COLUMN "TEAM4_202011F"."FILES"."FILE_PATH" IS '파일 경로';
   COMMENT ON COLUMN "TEAM4_202011F"."FILES"."FILE_ORIGIN" IS '파일 원본명';
   COMMENT ON COLUMN "TEAM4_202011F"."FILES"."FILE_SAVE" IS '파일 저장명';
   COMMENT ON COLUMN "TEAM4_202011F"."FILES"."FILE_TYPE" IS '파일 유형';
   COMMENT ON COLUMN "TEAM4_202011F"."FILES"."FILE_DEL" IS '파일 삭제 여부';
   COMMENT ON TABLE "TEAM4_202011F"."FILES"  IS '통합첨부파일';
