--------------------------------------------------------
--  DDL for Table LACTION
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."LACTION" 
   (	"LACTION_NO" NUMBER, 
	"LACTION_CONT" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" ;

   COMMENT ON COLUMN "TEAM4_202011F"."LACTION"."LACTION_NO" IS '신고 조치 일련 번호';
   COMMENT ON COLUMN "TEAM4_202011F"."LACTION"."LACTION_CONT" IS '신고 조치 설명';
   COMMENT ON TABLE "TEAM4_202011F"."LACTION"  IS '신고 조치 분류';
