--------------------------------------------------------
--  DDL for Table MENU_AUTH
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."MENU_AUTH" 
   (	"MENU_ID" VARCHAR2(12 BYTE), 
	"AUTH_CODE" VARCHAR2(2 BYTE), 
	"AUTH_READ" VARCHAR2(1 BYTE), 
	"AUTH_WRITE" VARCHAR2(1 BYTE), 
	"AUTH_DEL" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" ;
