--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."MENU" 
   (	"MENU_ID" VARCHAR2(12 BYTE), 
	"UPPER_MENU_ID" VARCHAR2(12 BYTE), 
	"MENU_SE" VARCHAR2(2 BYTE), 
	"MENU_ORD" NUMBER, 
	"MENU_NAME" VARCHAR2(50 BYTE), 
	"MENU_DESC" VARCHAR2(100 BYTE), 
	"MENU_URL" VARCHAR2(100 BYTE), 
	"MENU_DEL" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" ;
