--------------------------------------------------------
--  DDL for Table PROD
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."PROD" 
   (	"PROD_CODE" VARCHAR2(12 BYTE), 
	"LPROD_ID" VARCHAR2(2 BYTE), 
	"PROD_NAME" VARCHAR2(50 BYTE), 
	"PROD_PRICE" NUMBER, 
	"FC_ID" VARCHAR2(12 BYTE), 
	"LPROD_CODE" VARCHAR2(12 BYTE), 
	"PROD_DEL" CHAR(1 BYTE) DEFAULT 'N', 
	"PROD_PHOTO" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" ;

   COMMENT ON COLUMN "TEAM4_202011F"."PROD"."PROD_CODE" IS '판매 상품 코드';
   COMMENT ON COLUMN "TEAM4_202011F"."PROD"."LPROD_ID" IS '상품 분류';
   COMMENT ON COLUMN "TEAM4_202011F"."PROD"."PROD_NAME" IS '판매 상품 이름';
   COMMENT ON COLUMN "TEAM4_202011F"."PROD"."PROD_PRICE" IS '판매 상품 가격';
   COMMENT ON COLUMN "TEAM4_202011F"."PROD"."FC_ID" IS '이용 시설물 아이디';
   COMMENT ON TABLE "TEAM4_202011F"."PROD"  IS '판매 상품';
