--------------------------------------------------------
--  DDL for Table REPORT
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."REPORT" 
   (	"REPORT_NO" NUMBER, 
	"EMP_ID" VARCHAR2(12 BYTE), 
	"REPORT_TITLE" VARCHAR2(100 BYTE), 
	"REPORT_CONT" CLOB, 
	"REPORT_DATE" VARCHAR2(8 BYTE), 
	"LREPORT_CODE" VARCHAR2(2 BYTE), 
	"REPORT_DEL" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"FILE_NO" NUMBER, 
	"REPORT_APP_NEED" CHAR(1 BYTE) DEFAULT 'N', 
	"REPORT_MONEY" VARCHAR2(100 BYTE) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" 
 LOB ("REPORT_CONT") STORE AS BASICFILE (
  TABLESPACE "TS_202011F" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "TEAM4_202011F"."REPORT"."REPORT_NO" IS '보고서 일련 번호';
   COMMENT ON COLUMN "TEAM4_202011F"."REPORT"."EMP_ID" IS '보고서 작성자';
   COMMENT ON COLUMN "TEAM4_202011F"."REPORT"."REPORT_TITLE" IS '보고서 제목';
   COMMENT ON COLUMN "TEAM4_202011F"."REPORT"."REPORT_CONT" IS '보고서 내용';
   COMMENT ON COLUMN "TEAM4_202011F"."REPORT"."REPORT_DATE" IS '보고서 작성일자';
   COMMENT ON COLUMN "TEAM4_202011F"."REPORT"."LREPORT_CODE" IS '보고서 분류 코드';
   COMMENT ON COLUMN "TEAM4_202011F"."REPORT"."REPORT_DEL" IS '보고서 삭제 여부';
   COMMENT ON COLUMN "TEAM4_202011F"."REPORT"."FILE_NO" IS '통합첨부파일번호';
   COMMENT ON COLUMN "TEAM4_202011F"."REPORT"."REPORT_APP_NEED" IS '보고서 승인 필요 여부';
   COMMENT ON COLUMN "TEAM4_202011F"."REPORT"."REPORT_MONEY" IS '돈';
   COMMENT ON TABLE "TEAM4_202011F"."REPORT"  IS '보고서';
