--------------------------------------------------------
--  DDL for Table SALARY
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."SALARY" 
   (	"SAL_NO" NUMBER, 
	"EMP_ID" VARCHAR2(12 BYTE), 
	"SAL_AMOUNT" NUMBER, 
	"SAL_CONT" VARCHAR2(300 BYTE), 
	"SAL_DATE" VARCHAR2(8 BYTE), 
	"SAL_NATION" NUMBER, 
	"SAL_EMPINS" NUMBER, 
	"SAL_SAFE" NUMBER, 
	"SAL_HEALTH" NUMBER, 
	"SAL_PLUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" ;

   COMMENT ON COLUMN "TEAM4_202011F"."SALARY"."SAL_NO" IS '직원 급여 일련 번호';
   COMMENT ON COLUMN "TEAM4_202011F"."SALARY"."EMP_ID" IS '직원 아이디';
   COMMENT ON COLUMN "TEAM4_202011F"."SALARY"."SAL_AMOUNT" IS '직원 급여';
   COMMENT ON COLUMN "TEAM4_202011F"."SALARY"."SAL_CONT" IS '직원 급여 내용';
   COMMENT ON COLUMN "TEAM4_202011F"."SALARY"."SAL_DATE" IS '지급 날짜';
   COMMENT ON COLUMN "TEAM4_202011F"."SALARY"."SAL_NATION" IS '국민연금';
   COMMENT ON COLUMN "TEAM4_202011F"."SALARY"."SAL_EMPINS" IS '고용보험';
   COMMENT ON COLUMN "TEAM4_202011F"."SALARY"."SAL_SAFE" IS '산재보험';
   COMMENT ON COLUMN "TEAM4_202011F"."SALARY"."SAL_HEALTH" IS '건강보험';
   COMMENT ON COLUMN "TEAM4_202011F"."SALARY"."SAL_PLUS" IS '추가 근무 수당';
