--------------------------------------------------------
--  DDL for Table SALE
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."SALE" 
   (	"SALE_ID" VARCHAR2(12 BYTE), 
	"SALE_NAME" VARCHAR2(50 BYTE), 
	"SALE_PERCENT" NUMBER, 
	"SALE_WAY" VARCHAR2(10 BYTE), 
	"SALE_WHO" VARCHAR2(50 BYTE), 
	"SALE_START" DATE, 
	"SALE_END" DATE, 
	"REMARK" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" ;

   COMMENT ON COLUMN "TEAM4_202011F"."SALE"."SALE_ID" IS '할인 아이디';
   COMMENT ON COLUMN "TEAM4_202011F"."SALE"."SALE_NAME" IS '할인 명';
   COMMENT ON COLUMN "TEAM4_202011F"."SALE"."SALE_PERCENT" IS '할인율';
   COMMENT ON COLUMN "TEAM4_202011F"."SALE"."SALE_WAY" IS '할인 적용 방법';
   COMMENT ON COLUMN "TEAM4_202011F"."SALE"."SALE_WHO" IS '할인적용대상';
   COMMENT ON COLUMN "TEAM4_202011F"."SALE"."SALE_START" IS '할인시작날짜';
   COMMENT ON COLUMN "TEAM4_202011F"."SALE"."SALE_END" IS '할인종료날짜';
   COMMENT ON COLUMN "TEAM4_202011F"."SALE"."REMARK" IS '비고';
   COMMENT ON TABLE "TEAM4_202011F"."SALE"  IS '할인정책';
