--------------------------------------------------------
--  DDL for Table TICKET
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."TICKET" 
   (	"TICKET_ID" VARCHAR2(12 BYTE), 
	"TICKET_NAME" VARCHAR2(50 BYTE), 
	"TICKET_TYPE" VARCHAR2(2 BYTE), 
	"TICKET_AGE" VARCHAR2(2 BYTE), 
	"TICKET_PRICE" NUMBER, 
	"TICKET_SALE" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"REMARK" VARCHAR2(500 BYTE), 
	"TICKET_GRP" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" ;

   COMMENT ON COLUMN "TEAM4_202011F"."TICKET"."TICKET_ID" IS '이용권아이디';
   COMMENT ON COLUMN "TEAM4_202011F"."TICKET"."TICKET_NAME" IS '이용권이름';
   COMMENT ON COLUMN "TEAM4_202011F"."TICKET"."TICKET_TYPE" IS '이용권종류';
   COMMENT ON COLUMN "TEAM4_202011F"."TICKET"."TICKET_AGE" IS '이용권연령';
   COMMENT ON COLUMN "TEAM4_202011F"."TICKET"."TICKET_PRICE" IS '이용권가격';
   COMMENT ON COLUMN "TEAM4_202011F"."TICKET"."TICKET_SALE" IS '할인가능여부';
   COMMENT ON COLUMN "TEAM4_202011F"."TICKET"."REMARK" IS '비고';
   COMMENT ON TABLE "TEAM4_202011F"."TICKET"  IS '이용권';
