--------------------------------------------------------
--  DDL for Table UBOARD
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."UBOARD" 
   (	"UBOARD_NO" NUMBER, 
	"UBOARD_TITLE" VARCHAR2(100 BYTE), 
	"UBOARD_CONT" CLOB, 
	"UBOARD_DEL" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"LUBOARD_CODE" VARCHAR2(2 BYTE), 
	"LLOST_CODE" VARCHAR2(2 BYTE), 
	"FILE_NO" NUMBER, 
	"UBOARD_DATE" VARCHAR2(8 BYTE), 
	"UBOARD_HIT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" 
 LOB ("UBOARD_CONT") STORE AS BASICFILE (
  TABLESPACE "TS_202011F" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "TEAM4_202011F"."UBOARD"."UBOARD_NO" IS '고객 대응 게시판 일련 번호';
   COMMENT ON COLUMN "TEAM4_202011F"."UBOARD"."UBOARD_TITLE" IS '고객 대응 게시글 제목';
   COMMENT ON COLUMN "TEAM4_202011F"."UBOARD"."UBOARD_CONT" IS '고객 대응 게시글 내용';
   COMMENT ON COLUMN "TEAM4_202011F"."UBOARD"."UBOARD_DEL" IS '고객 대응 게시글 삭제 여부';
   COMMENT ON COLUMN "TEAM4_202011F"."UBOARD"."LUBOARD_CODE" IS '고객 대응 게시판 분류 코드';
   COMMENT ON COLUMN "TEAM4_202011F"."UBOARD"."LLOST_CODE" IS '분실 유실 분류';
   COMMENT ON COLUMN "TEAM4_202011F"."UBOARD"."FILE_NO" IS '통합첨부파일번호';
   COMMENT ON COLUMN "TEAM4_202011F"."UBOARD"."UBOARD_DATE" IS '고객 대응 게시글 일자';
   COMMENT ON COLUMN "TEAM4_202011F"."UBOARD"."UBOARD_HIT" IS '고객 대응 게시글 조회수';
   COMMENT ON TABLE "TEAM4_202011F"."UBOARD"  IS '고객대응게시판';
