--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."USERS" 
   (	"USER_ID" VARCHAR2(12 BYTE), 
	"USER_PASS" VARCHAR2(150 BYTE), 
	"USER_NAME" VARCHAR2(50 BYTE), 
	"USER_REG" VARCHAR2(7 BYTE), 
	"USER_MAIL" VARCHAR2(40 BYTE), 
	"USER_HP" VARCHAR2(11 BYTE), 
	"USER_PROTECT" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"USER_DEL" DATE, 
	"USER_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" ;

   COMMENT ON COLUMN "TEAM4_202011F"."USERS"."USER_ID" IS '회원아이디';
   COMMENT ON COLUMN "TEAM4_202011F"."USERS"."USER_PASS" IS '회원비밀번호';
   COMMENT ON COLUMN "TEAM4_202011F"."USERS"."USER_NAME" IS '회원명';
   COMMENT ON COLUMN "TEAM4_202011F"."USERS"."USER_REG" IS '회원주민번호';
   COMMENT ON COLUMN "TEAM4_202011F"."USERS"."USER_MAIL" IS '회원이메일';
   COMMENT ON COLUMN "TEAM4_202011F"."USERS"."USER_HP" IS '회원전화번호';
   COMMENT ON COLUMN "TEAM4_202011F"."USERS"."USER_PROTECT" IS '회원 보호 계정 여부';
   COMMENT ON COLUMN "TEAM4_202011F"."USERS"."USER_DEL" IS '탈퇴일시';
   COMMENT ON COLUMN "TEAM4_202011F"."USERS"."USER_DATE" IS '가입일시';
   COMMENT ON TABLE "TEAM4_202011F"."USERS"  IS '회원';
