--------------------------------------------------------
--  DDL for Table VACATION
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."VACATION" 
   (	"VAC_NO" NUMBER, 
	"EMP_ID" VARCHAR2(12 BYTE), 
	"VAC_USE" NUMBER, 
	"VAC_USE_START" VARCHAR2(8 BYTE), 
	"VAC_USE_END" VARCHAR2(8 BYTE), 
	"LVAC_CODE" VARCHAR2(2 BYTE), 
	"VAC_REASON" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" ;

   COMMENT ON COLUMN "TEAM4_202011F"."VACATION"."VAC_NO" IS '휴가 일련 번호';
   COMMENT ON COLUMN "TEAM4_202011F"."VACATION"."EMP_ID" IS '직원아이디';
   COMMENT ON COLUMN "TEAM4_202011F"."VACATION"."VAC_USE" IS '사용 휴가';
   COMMENT ON COLUMN "TEAM4_202011F"."VACATION"."VAC_USE_START" IS '사용 시작 일자';
   COMMENT ON COLUMN "TEAM4_202011F"."VACATION"."VAC_USE_END" IS '사용 종료 일자';
   COMMENT ON COLUMN "TEAM4_202011F"."VACATION"."LVAC_CODE" IS '휴가 분류';
   COMMENT ON COLUMN "TEAM4_202011F"."VACATION"."VAC_REASON" IS '휴가 사유';
   COMMENT ON TABLE "TEAM4_202011F"."VACATION"  IS '사용 휴가 내역';
