--------------------------------------------------------
--  DDL for Table WORK
--------------------------------------------------------

  CREATE TABLE "TEAM4_202011F"."WORK" 
   (	"WORK_NO" NUMBER, 
	"EMP_ID" VARCHAR2(12 BYTE), 
	"LWORK_CODE" VARCHAR2(2 BYTE), 
	"WORK_DATE" VARCHAR2(8 BYTE), 
	"WORK_START" VARCHAR2(20 BYTE), 
	"WORK_END" VARCHAR2(20 BYTE), 
	"WORK_PLUS" NUMBER, 
	"WORK_BACK" VARCHAR2(8 BYTE) DEFAULT '#D25565', 
	"WORK_TEXT" VARCHAR2(8 BYTE) DEFAULT '#FFFFFF', 
	"WORK_TITLE" VARCHAR2(120 BYTE) DEFAULT '근무'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202011F" ;
