--------------------------------------------------------
--  Ref Constraints for Table AGREEMENT
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."AGREEMENT" ADD CONSTRAINT "FK_CLAUSE_TO_AGREEMENT" FOREIGN KEY ("CLAUSE_NO")
	  REFERENCES "TEAM4_202011F"."CLAUSE" ("CLAUSE_NO") ENABLE;
  ALTER TABLE "TEAM4_202011F"."AGREEMENT" ADD CONSTRAINT "FK_USERS_TO_AGREEMENT" FOREIGN KEY ("USER_ID")
	  REFERENCES "TEAM4_202011F"."USERS" ("USER_ID") ENABLE;
