--------------------------------------------------------
--  Ref Constraints for Table ALARM_RECEIVER
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."ALARM_RECEIVER" ADD CONSTRAINT "FK_ALARM_ALARM_RECEIVER" FOREIGN KEY ("ALARM_NO")
	  REFERENCES "TEAM4_202011F"."ALARM" ("ALARM_NO") ENABLE;
  ALTER TABLE "TEAM4_202011F"."ALARM_RECEIVER" ADD CONSTRAINT "FK_EMP_ALARM_RECEIVER" FOREIGN KEY ("EMP_ID")
	  REFERENCES "TEAM4_202011F"."EMP" ("EMP_ID") ENABLE;
