--------------------------------------------------------
--  Ref Constraints for Table LACTION_SELECT
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."LACTION_SELECT" ADD CONSTRAINT "FK_ACCUSE_TO_LACTION_SELECT" FOREIGN KEY ("ACCUSE_NO")
	  REFERENCES "TEAM4_202011F"."ACCUSE" ("ACCUSE_NO") ENABLE;
  ALTER TABLE "TEAM4_202011F"."LACTION_SELECT" ADD CONSTRAINT "FK_LACTION_TO_LACTION_SELECT" FOREIGN KEY ("LACTION_NO")
	  REFERENCES "TEAM4_202011F"."LACTION" ("LACTION_NO") ENABLE;
