--------------------------------------------------------
--  Ref Constraints for Table MEMBERSHIP
--------------------------------------------------------

  ALTER TABLE "TEAM4_202011F"."MEMBERSHIP" ADD CONSTRAINT "FK_RES_INFO_TO_MEMBERSHIP" FOREIGN KEY ("RES_INFO_CODE")
	  REFERENCES "TEAM4_202011F"."RES_INFO" ("RES_INFO_CODE") ENABLE;
  ALTER TABLE "TEAM4_202011F"."MEMBERSHIP" ADD CONSTRAINT "FK_USERS_MEMBERSHIP" FOREIGN KEY ("USER_ID")
	  REFERENCES "TEAM4_202011F"."USERS" ("USER_ID") ENABLE;
